export { default as Loader} from './Loader';
export { default as Navbar} from './Navbar';
export { default as Footer} from './Footer';
export { default as Welcome} from './Welcome';
export { default as Services} from './Services';
export { default as Team} from './Team';
export { default as Home} from './Home';
export { default as Upload} from './Upload';
export { default as View} from './View';
export { default as Tutorial} from './Tutorial';
export { default as Profile} from './Profile';
export {default as Nopage} from './Nopage';
export {default as Create} from './Create';
export { default as Verify} from './Verify';
export {default as Login} from './Login';
export { default as Signup} from './Signup';